#!/bin/sh

date '+%H:%M:%S %a %d-%m-%Y '

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send "Date" "$(cal --color=always -m | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "$(calcurse -d3)" ;;
esac
