#!/bin/sh

case $BLOCK_BUTTON in
	1) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
esac


vol=$(pulsemixer --get-volume | awk '{print $1}')


if [ "$(pulsemixer --get-mute)" = "1" ]; then
	icon="🔇"
elif [ "$vol" -gt "70" ]; then
	icon="🔊"
elif [ "$vol" -lt "30" ]; then
	icon="🔈"
else
	icon="🔉"
fi

printf "%s %s%%\\n" "$icon" "$vol"
