#!/bin/sh

case $1 in
	status)		expressvpn status | sed 1q | sed 's/\x1b\[[0-9;]*m//g' | sed -E 's/(Connected to |Not connected)//';;

	menu)		chosen=$(expressvpn ls all | sed '1,2d' | dmenu -i | awk '{print $1}');
			if [ -z "$chosen" ];
			then
				exit
			else
				expressvpn disconnect; expressvpn connect "$chosen";
			fi;;

	disconnect) expressvpn disconnect;;
esac
